env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {"no-console": "off", "import/extensions": "off",  "import/prefer-default-export": "off", "no-undef": "off", "no-use-before-define": "off", "no-unused-vars": "off"}