name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: install airbnb config
      run: npm i eslint-config-airbnb
    - name: Run ESLint
      run: npx eslint --no-eslintrc --config .eslintrc.yml .
